all:
  children:

    proxmox_hosts:
      hosts:
        pve-01:
          ansible_host: *.*.*.*
          ansible_user: xyz
          ansible_ssh_private_key_file: ~/.ssh/homelab_id

    pve_lxc:
      hosts:
        nut-01:
          ansible_host: *.*.*.*  # VLAN * — match nut_lxc_ip in tfvars
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/homelab_id
        plex-01:
          ansible_host: *.*.*.*  # VLAN * — match plex_lxc_ip in tfvars
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/homelab_id
        monitoring-01:
          ansible_host: *.*.*.*  # VLAN * — match monitoring_lxc_ip in tfvars
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/homelab_id
        homeautomation-01:
          ansible_host: *.*.*.*  # VLAN * — match homeassistant_vm_ip in tfvars
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/homelab_id
        k3s-01:
          ansible_host: *.*.*.*  # VLAN * — match k3s_vm_ip in tfvars
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/homelab_id
